name: CI-CD

on: 
  push:
    branches: ["main"]
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0      
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          public.ecr.aws/i9w0w5o5/kube-news:v1
          public.ecr.aws/i9w0w5o5/kube-news:latest
