name: CI-CD

on: 
  push:
    branches: ["main"]
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          lucasortis/kube-news:${{github.workflow_sha}}
          lucasortis/kube-news:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Kubernetes Set Context
      uses: Azure/k8s-set-context@v3.0
      with:
        kubeconfig: ${{secrets.DEVELOPMENT_CLUSTER_KUBECONFIG}}

    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v4.9
      with:
        images: lucasortis/kube-news:${{github.workflow_sha}}
        manifests: ./k8s/deployment.yaml
    
      

    
